export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_EVENT_CHAT_TRYING_TO_JOIN = "SET_EVENT_CHAT_TRYING_TO_JOIN";
export const CREATE_EVENT_GROUP_PENDING = "CREATE_EVENT_GROUP_PENDING";
export const CREATE_EVENT_GROUP_SUCCESS = "CREATE_EVENT_GROUP_SUCCESS";
export const CREATE_EVENT_GROUP_FAILURE = "CREATE_EVENT_GROUP_FAILURE";

// update

export const UPDATE_EVENT_GROUP = "UPDATE_EVENT_GROUP";
